## Практическое задание

**Задание 1.** Найти с помощью NumPy SVD для матрицы

$$\begin{pmatrix}
1 & 2 & 0\\ 
0 & 0 & 5\\ 
3 & -4 & 2\\ 
1 & 6 & 5\\ 
0 & 1 & 0
\end{pmatrix}.$$



In [1]:
import numpy as np
np.set_printoptions(precision=2, suppress=True)

In [2]:
A = np.array([[1,2,0],[0,0,5],[3,-4,2],[1,6,5],[0,1,0]])
U, s, W = np.linalg.svd(A)
D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = s

In [3]:
print(f'U = \n{U}')

U = 
[[ 0.17  0.16 -0.53 -0.8  -0.16]
 [ 0.39 -0.53  0.61 -0.43  0.03]
 [-0.14 -0.82 -0.52  0.14  0.07]
 [ 0.89  0.06 -0.25  0.38 -0.06]
 [ 0.08  0.11 -0.08 -0.11  0.98]]


In [4]:
print(f'D = \n{D}')

D = 
[[8.82 0.   0.  ]
 [0.   6.14 0.  ]
 [0.   0.   2.53]
 [0.   0.   0.  ]
 [0.   0.   0.  ]]


In [5]:
print(f'W = \n{W}')

W = 
[[ 0.07  0.72  0.69]
 [-0.37  0.67 -0.65]
 [-0.93 -0.21  0.31]]


**Задание 2.** Для матрицы из предыдущего задания найти:

а) евклидову норму;
    
    

In [6]:
print(f'Ответ: {D.max()}')

Ответ: 8.824868854820442


б) норму Фробениуса

In [7]:
D_squared = np.square(D)
print(f'Ответ: {np.sqrt(D_squared.sum())}')

Ответ: 11.045361017187261
